### PR TITLE
#693  Clarify python version support (#2)

### PR DESCRIPTION
**Pull request by stheid**
* Added Classifiers to setup py, mainly language level
* add pypi and python version badge

### CODE REVIEW

**Comment by stheid** [comment]
one disclaimer maybe, the badge including the python version will show "missing" until the next release on pypi has been carried out. shields.io reads the python version from pypi

**Comment by AlexKuhnle** [comment]
Nice, looks good, thanks for adding this. And sorry, wasn't aware of that Python3.8 problem, but as mentioned in the issue, it will be gone addressed for master and pip soon.

**Comment by AlexKuhnle** [comment]
Just pushed 0.5.5 to pypi, but the Python version badge seems to not work, or am I missing something?

**Comment by stheid** [comment]
Hm, thats strange. The generated package metadata seems to be incomplete. I never had issues with that, therefore i dont know what caused this. maybe you can hide the badge temporarily.

https://stackoverflow.com/a/26284610/13310191

Pypi should usually show that classifiers section down on the left
image

With which command do you generate the package? 

https://github.com/upb-lea/openmodelica-microgrid-gym/blob/00e28db1fa0ab6350db413292a4ea10f626ee32c/.travis.yml#L43

**Comment by AlexKuhnle** [comment]
The package is created via `python setup.py sdist bdist_wheel`, so the same. And on pypi you can see [Requires: >= 3.5](https://pypi.org/project/Tensorforce/), but the classifiers are not there. No idea...

**Comment by AlexKuhnle** [comment]
They also don't show in the `PKG-INFO` file:

```
...
Platform: UNKNOWN
Requires-Python: >=3.5
Description-Content-Type: text/markdown
Provides-Extra: tf
Provides-Extra: tf_gpu
Provides-Extra: tfa
Provides-Extra: docs
Provides-Extra: tune
Provides-Extra: envs
Provides-Extra: mazeexp
Provides-Extra: gym
Provides-Extra: retro
Provides-Extra: vizdoom
Provides-Extra: carla
```

**Comment by stheid** [comment]
```
> git clone git@github.com:tensorforce/tensorforce.git
> cd tensorforce/
> python setup.py sdist
> cat Tensorforce.egg-info/PKG-INFO |grep Classifier
Classifier: Natural Language :: English
Classifier: Topic :: Scientific/Engineering
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.7
```

It works on my machine with your master code. So the code is definetly correct. Maybe update your Setuptools libary? which setuptools version do you have and which platform? Which metadata verision did your python code generate?

Once again it looks similar to stackoverflow.com/a/26284610/13310191

**Comment by AlexKuhnle** [comment]
Hmm, maybe it's setuptools, not sure I've updated it recently. I'll check later.

**Comment by AlexKuhnle** [comment]
Sorry, had forgotten about this: My setuptools version was 45.2.0.

**Comment by stheid** [comment]
but did it work now?

**Comment by AlexKuhnle** [comment]
Sorry, didn't have time to check yesterday, but did now, and yes, it seems to work now:

```
...
Platform: UNKNOWN
Classifier: Natural Language :: English
Classifier: Topic :: Scientific/Engineering
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.7
Requires-Python: >=3.5
Description-Content-Type: text/markdown
Provides-Extra: tf
Provides-Extra: tf_gpu
Provides-Extra: tfa
...
```

Thanks for this, will be included in the next version then.

**Pull request merged**
