### PR TITLE
Fix global variable naming in model.py

### PR DESCRIPTION
**Pull request by rshtirmer**
Fix global variable naming in model.py. I got an error about this issue when making a "flatten" layer, and this fixes the issue.

### CODE REVIEW

**Comment by AlexKuhnle** [comment]
Hi, could you give more information about the error you got? As far as I can tell, this renaming shouldn't work. (See the name of the global tensors e.g. [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/module.py#L345))

**Comment by rshtirmer** [comment]
Interesting, the error was essentially that self.global_episode does not exist, which went away after renaming.

**Comment by AlexKuhnle** [comment]
Hmm, so it doesn't need fixing after all?

**Comment by rshtirmer** [comment]
@AlexKuhnle Well, no... the changes I made were renaming... which is what fixed it.. If you'd like I can get you a copy of the error log.

**Comment by AlexKuhnle** [comment]
Hmm, that is weird, since the names of the variables seem to be "singular", so `global_episode` etc, as can be seen in the link above, but your changes suggest they should be in plural, `global_episodes`. A copy of the exception would be very helpful. Also, just to check: Are you on the latest master version?

**Comment by AlexKuhnle** [comment]
I will close this PR due to inactivity.

**Pull request closed without merging**
