### PR TITLE
Fixing a bug whereby normalize values was referencing an incorrect variable when doing a lookup.

### PR DESCRIPTION
**Pull request by codeninja**
I believe normalize values was doing a lookup on the wrong variable.  

`value = value[name]` would equate to [0, .... N][string] which throws an error.

I believe the intent was to normalize the name and then locate the value within the values_spec.

### CODE REVIEW

**Comment by AlexKuhnle** [comment]
Hi, do you have a simple example where this breaks? May well be that there is a bug somewhere, but from a very first look this line doesn't look "wrong" to me. Anyway, will properly look into it later. Thanks for raising!

**Comment by AlexKuhnle** [comment]
A situation where this causes a problem would be great, as I'm quite sure this part generally looks as intended, but there may of course be a bug with it being used wrongly.

**Comment by codeninja** [comment]
I will post an example later today.

Thanks,
Dallas
---------------------------------------
*Professional leader of highly preformant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by codeninja** [comment]
You'll notice from the code pasted below that I have reproduced the issue using the master branch of Tensorforce 0.5.1. In this code I am normalizing my dataframe values.

The issue I'm seeing (as you'll see from the shot below) 
image

Line 720sets `value=values' which equates to:

`value: [[0.       0.       0.       0.       0.000534]]`

While the name we're trying to look up on line 726 evaluates to:

`normalized name: gymbox0`

What I believe we should be referencing here is the **values_spec**

`value_spec: OrderedDict([('gymbox0', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox1', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox2', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox3', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox4', {'type': 'float', 'shape': (), 'min_value': 0.0001, 'max_value': 1000000.0})])`



```
Timesteps:   0%|                                                              | 0/200 [00:00<?, ?it/s, mean_reward=n/a]C:\Users\codeninja\Anaconda3\envs\tensortrade\lib\site-packages\tensortrade\features\scalers\min_max_normalizer.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[column] = normalized_column
C:\Users\codeninja\Anaconda3\envs\tensortrade\lib\site-packages\tensortrade\features\stationarity\fractional_difference.py:127: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[column] = diffed_series.fillna(method='bfill')

normalized name: gymbox0

value: [[0.       0.       0.       0.       0.000534]]

value_spec: OrderedDict([('gymbox0', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox1', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox2', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox3', {'type': 'float', 'shape': (), 'min_value': 1e-06, 'max_value': 1000000.0}), ('gymbox4', {'type': 'float', 'shape': (), 'min_value': 0.0001, 'max_value': 1000000.0})])

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-5bd8354eb338> in <module>
----> 1 performance = strategy.run(steps=200)

~\Anaconda3\envs\tensortrade\lib\site-packages\tensortrade\strategies\tensorforce_trading_strategy.py in run(self, steps, episodes, evaluation, episode_callback)
    106                          num_episodes=episodes,
    107                          # max_episode_timesteps=self._max_episode_timesteps,
--> 108                          callback=episode_callback)
    109 
    110         n_episodes = self._runner.episodes

~\Anaconda3\envs\tensortrade\lib\site-packages\tensorforce\execution\runner.py in run(self, num_episodes, num_timesteps, num_updates, max_episode_timesteps, num_repeat_actions, callback, callback_episode_frequency, callback_timestep_frequency, use_tqdm, mean_horizon, evaluation, evaluation_callback, evaluation_frequency, max_evaluation_timesteps, num_evaluation_iterations)
    231             if not self.run_episode(
    232                 environment=self.environment, max_timesteps=self.max_episode_timesteps,
--> 233                 evaluation=self.evaluation
    234             ):
    235                 return

~\Anaconda3\envs\tensortrade\lib\site-packages\tensorforce\execution\runner.py in run_episode(self, environment, max_timesteps, evaluation)
    324             # Retrieve actions from agent
    325             agent_start = time.time()
--> 326             actions = self.agent.act(states=states, evaluation=evaluation)
    327             self.timesteps += 1
    328             self.episode_agent_second += time.time() - agent_start

~\Anaconda3\envs\tensortrade\lib\site-packages\tensorforce\agents\agent.py in act(self, states, parallel, deterministic, independent, evaluation, query, **kwargs)
    304         # Normalize states dictionary
    305         states = util.normalize_values(
--> 306             value_type='state', values=states, values_spec=self.states_spec
    307         )
    308 

~\Anaconda3\envs\tensortrade\lib\site-packages\tensorforce\util.py in normalize_values(value_type, values, values_spec)
    723         print("value_spec:", values_spec)
    724         for name in normalized_name.split('/'):
--> 725             value = value[name]
    726         normalized_values[normalized_name] = value
    727 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

**Comment by AlexKuhnle** [comment]
Hi, thanks for the details. From what you posted, I actually think that it's a wrong handling of box space type in the OpenAIGym environment [here](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/environments/openai_gym.py#L281). Could you post the following output: `environment.states()`, `environment.actions()`, and `environment.reset()`? Alternatively, if it's a standard Gym environment you're using, you can just let me know the environment, and I can try it myself.

**Comment by codeninja** [comment]
[image: image.png]

Thanks,
Dallas
---------------------------------------
*Professional leader of highly preformant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by AlexKuhnle** [comment]
Posting that image didn't work, I think...

**Comment by codeninja** [comment]
image

**Comment by AlexKuhnle** [comment]
Cool, thanks, will look into it soon.

**Comment by AlexKuhnle** [comment]
Could you check the latest commit? I hope that fix works...

**Comment by codeninja** [comment]
Will do. I'll let you know.

**Comment by codeninja** [comment]
That did it! Thanks for the support!

**Pull request closed without merging**
